[project]
name = "durak"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "durakonline-py>=3.7.1",
    "loguru>=0.7.3",
    "psutil>=7.0.0",
    "requests>=2.32.5",
    "rstr>=3.2.2",
    "xeger>=0.4.0",
]
